apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  description: Infrastructure and platform services

  # Allow deployments to specific namespaces
  destinations:
    - namespace: 'kube-system'
      server: 'https://kubernetes.default.svc'
    - namespace: 'amazon-cloudwatch'
      server: 'https://kubernetes.default.svc'
    - namespace: 'monitoring'
      server: 'https://kubernetes.default.svc'
    - namespace: 'ingress-nginx'
      server: 'https://kubernetes.default.svc'
    - namespace: 'cert-manager'
      server: 'https://kubernetes.default.svc'
    - namespace: 'external-secrets'
      server: 'https://kubernetes.default.svc'

  # Allow all resources
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  # Source repositories
  sourceRepos:
    - 'https://github.com/Partridje/aws-eks-production.git'
    - 'https://github.com/argoproj/argo-helm'
    - 'https://kubernetes-sigs.github.io/metrics-server/'
    - 'https://aws.github.io/eks-charts'
    - 'https://kubernetes.github.io/ingress-nginx'
    - 'https://charts.jetstack.io'
    - 'https://charts.external-secrets.io'
    - 'https://prometheus-community.github.io/helm-charts'
    - 'https://grafana.github.io/helm-charts'

  # RBAC policies
  roles:
    - name: infrastructure-admin
      description: Admin role for infrastructure project
      policies:
        - p, proj:infrastructure:infrastructure-admin, applications, *, infrastructure/*, allow
      groups:
        - admin
